-- MySQL Script generated by MySQL Workbench
-- Wed Jul 16 09:28:31 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema villes_monde_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema villes_monde_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `villes_monde_db` DEFAULT CHARACTER SET utf8 ;
USE `villes_monde_db` ;

-- -----------------------------------------------------
-- Table `villes_monde_db`.`continents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `villes_monde_db`.`continents` (
  `id_continent` INT NOT NULL AUTO_INCREMENT,
  `name_continent` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_continent`),
  UNIQUE INDEX `name_continent_UNIQUE` (`name_continent` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `villes_monde_db`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `villes_monde_db`.`countries` (
  `id_country` INT NOT NULL AUTO_INCREMENT,
  `name_country` VARCHAR(50) NOT NULL,
  `iso_country` VARCHAR(2) NOT NULL,
  `fk_id_continent` INT NULL,
  PRIMARY KEY (`id_country`),
  UNIQUE INDEX `name_country_UNIQUE` (`name_country` ASC) VISIBLE,
  UNIQUE INDEX `iso_country_UNIQUE` (`iso_country` ASC) VISIBLE,
  INDEX `fk_id_continent_idx` (`fk_id_continent` ASC) VISIBLE,
  CONSTRAINT `fk_id_continent`
    FOREIGN KEY (`fk_id_continent`)
    REFERENCES `villes_monde_db`.`continents` (`id_continent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `villes_monde_db`.`regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `villes_monde_db`.`regions` (
  `id_region` INT NOT NULL AUTO_INCREMENT,
  `name_region` VARCHAR(50) NOT NULL,
  `fk_id_country` INT NULL,
  PRIMARY KEY (`id_region`),
  INDEX `fk_id_country_idx` (`fk_id_country` ASC) VISIBLE,
  CONSTRAINT `fk_id_country`
    FOREIGN KEY (`fk_id_country`)
    REFERENCES `villes_monde_db`.`countries` (`id_country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `villes_monde_db`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `villes_monde_db`.`cities` (
  `id_city` INT NOT NULL AUTO_INCREMENT,
  `name_city` VARCHAR(50) NOT NULL,
  `area_city` FLOAT NOT NULL,
  `pop_city` BIGINT NOT NULL,
  `fk_id_region` INT NULL,
  PRIMARY KEY (`id_city`),
  INDEX `fk_id_region_idx` (`fk_id_region` ASC) VISIBLE,
  CONSTRAINT `fk_id_region`
    FOREIGN KEY (`fk_id_region`)
    REFERENCES `villes_monde_db`.`regions` (`id_region`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
