insert into regions (name_region, fk_id_country) values ('donec odio', 17);
insert into regions (name_region, fk_id_country) values ('vestibulum', 1);
insert into regions (name_region, fk_id_country) values ('orci luctus', 3);
insert into regions (name_region, fk_id_country) values ('a', 9);
insert into regions (name_region, fk_id_country) values ('vel', 5);
insert into regions (name_region, fk_id_country) values ('mattis odio', 14);
insert into regions (name_region, fk_id_country) values ('sed vel', 5);
insert into regions (name_region, fk_id_country) values ('sed sagittis', 7);
insert into regions (name_region, fk_id_country) values ('vel est', 5);
insert into regions (name_region, fk_id_country) values ('vestibulum', 10);
insert into regions (name_region, fk_id_country) values ('dui vel', 15);
insert into regions (name_region, fk_id_country) values ('felis eu', 9);
insert into regions (name_region, fk_id_country) values ('sed', 7);
insert into regions (name_region, fk_id_country) values ('at feugiat', 11);
insert into regions (name_region, fk_id_country) values ('lorem integer', 17);
insert into regions (name_region, fk_id_country) values ('convallis', 2);
insert into regions (name_region, fk_id_country) values ('luctus et', 15);
insert into regions (name_region, fk_id_country) values ('dapibus', 19);
insert into regions (name_region, fk_id_country) values ('luctus tincidunt', 2);
insert into regions (name_region, fk_id_country) values ('iaculis congue', 1);
insert into regions (name_region, fk_id_country) values ('eu', 2);
insert into regions (name_region, fk_id_country) values ('aliquam non', 13);
insert into regions (name_region, fk_id_country) values ('vel nulla', 19);
insert into regions (name_region, fk_id_country) values ('id', 16);
insert into regions (name_region, fk_id_country) values ('pede posuere', 2);
insert into regions (name_region, fk_id_country) values ('odio', 14);
insert into regions (name_region, fk_id_country) values ('congue', 18);
insert into regions (name_region, fk_id_country) values ('eget rutrum', 17);
insert into regions (name_region, fk_id_country) values ('justo nec', 7);
insert into regions (name_region, fk_id_country) values ('non velit', 8);
insert into regions (name_region, fk_id_country) values ('aliquam', 12);
insert into regions (name_region, fk_id_country) values ('nibh', 18);
insert into regions (name_region, fk_id_country) values ('leo', 17);
insert into regions (name_region, fk_id_country) values ('nascetur', 17);
insert into regions (name_region, fk_id_country) values ('augue luctus', 1);
insert into regions (name_region, fk_id_country) values ('accumsan', 16);
insert into regions (name_region, fk_id_country) values ('leo rhoncus', 17);
insert into regions (name_region, fk_id_country) values ('nibh', 14);
insert into regions (name_region, fk_id_country) values ('sapien', 18);
insert into regions (name_region, fk_id_country) values ('luctus et', 11);
insert into regions (name_region, fk_id_country) values ('scelerisque mauris', 4);
insert into regions (name_region, fk_id_country) values ('libero', 8);
insert into regions (name_region, fk_id_country) values ('lectus', 16);
insert into regions (name_region, fk_id_country) values ('sit', 18);
insert into regions (name_region, fk_id_country) values ('molestie', 3);
insert into regions (name_region, fk_id_country) values ('et magnis', 3);
insert into regions (name_region, fk_id_country) values ('aliquam', 6);
insert into regions (name_region, fk_id_country) values ('sapien ut', 9);
insert into regions (name_region, fk_id_country) values ('sagittis', 6);
insert into regions (name_region, fk_id_country) values ('nisl duis', 3);
